# Generated by Django 3.2.8 on 2021-11-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_reciperequirement_menu_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeRequirement',
        ),
    ]
